version: '6'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - get_task.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
